export const PROJECT = {
  slide: [
    {
      images: [
        {
          color: "#000000",
          src: "pwpv2.png",
          code: "P0000",
          due: "2023",
          title: "포트폴리오 V2",
          description: "Portfolio WEB Page Development",
          skill: ["React", "Next.js", "Tailwind CSS", "Framer"],
          info: ["제작", "개발"],
          role: [],
          purpose: [],
          result: [],
          link: [],
        },
        {
          color: "#8C8C8C",
          src: "dbv2.png",
          code: "P0001",
          title: "개발 블로그 V2",
          skill: ["React", "Next.js", "Tailwind CSS", "Framer"],
          info: ["제작"],
        },
        {
          color: "#EFE8D3",
          src: "resume.png",
          code: "P0002",
          title: "RESUME",
          skill: ["React", "Next.js", "Tailwind CSS", "Framer"],
          info: ["제작"],
        },
        {
          color: "#706D63",
          src: "pwpv1.png",
          code: "P0003",
          title: "포트폴리오 V1",
          skill: ["React", "Next.js", "Tailwind CSS", "Framer"],
          info: ["제작"],
        },
      ],
    },
    {
      images: [
        {
          color: "#000000",
          src: "aptinfo.png",
          code: "P0004",
          title: "아파트 홍보 페이지",
          skill: ["React", "Next.js", "Tailwind CSS", "Framer"],
          info: ["제작"],
        },
        {
          color: "#8C8C8C",
          src: "mern.png",
          code: "P0005",
          title: "개발 블로그 V1",
          skill: ["React", "Next.js", "Tailwind CSS", "Framer"],
          info: ["제작"],
        },
        {
          color: "#EFE8D3",
          src: "auto.png",
          code: "P0006",
          title: "코인 오토트레이딩 프로그램",
          skill: ["React", "Next.js", "Tailwind CSS", "Framer"],
          info: ["제작"],
        },
        {
          color: "#706D63",
          src: "chat.png",
          code: "P0007",
          title: "Vue Chat Page",
          skill: ["React", "Next.js", "Tailwind CSS", "Framer"],
          info: ["제작"],
        },
      ],
    },
    {
      images: [
        {
          color: "#000000",
          src: "",
          code: "P0008",
          title: "OIPF STB WEB Page",
          skill: ["React", "Next.js", "Tailwind CSS", "Framer"],
          info: ["제작"],
        },
        {
          color: "#8C8C8C",
          src: "check.png",
          code: "P0009",
          title: "출섹체크 프로그램",
          skill: ["React", "Next.js", "Tailwind CSS", "Framer"],
          info: ["제작"],
        },
      ],
    },
  ],
};
