export const EXPERIENCE_RESUME = [
  {
    title: "(주)알티모빌리티 / 프론트엔드 개발자",
    team: "플랫폼개발팀 - 연구원",
    due: "2021.12.01 ~ 재직중 (2년 2개월)",
    img: "/images/career/altimobility.png",
    skill: [
      "React",
      "javascript",
      "Typescript",
      "Node.js",
      "Next.js",
      "Ant Design",
      "styledcomponents",
      "sass",
    ],
    project: [
      // {
      //   title: "DMS Admin Page F/E 설계 및 개발 (LG U+)",
      //   due: "2023-07 ~ 진행중",
      //   code: "C0017",
      //   description: "DMS 서비스 Admin Page F/E 설계 및 개발, 기능 관련 리딩",
      //   icon: "dev",
      //   skill: ["React", "Next.js", "Antdesign", "SASS", "Typescript"],
      //   info: ["LG U+ SI 프로젝트 DMS 시스템 개발"],
      //   role: [
      //     "Admin Page Boilerplate 이용하여 개발 진행",
      //     "발주/주문 관련 기능 설계 리딩 및 개발",
      //     "Ant-design, SASS 디자인 시스템 도입",
      //   ],
      //   purpose: [
      //     "다수의 주문(100건)의 안정적인 주문/발주 처리",
      //     "Device 설치기사 APP 과 안정적인 데이터 연동을 위한 설계",
      //   ],
      // },
      // {
      //   title: "Admin / BizPortal 향 Boiler Plate 개발 (연구과제)",
      //   due: "2023-02 ~ 2023-08",
      //   code: "C0001",
      //   description: "SI 프로젝트 기초 설계를 위한 Boiler Plate 개발",
      //   icon: "system",
      //   skill: ["Vite", "React", "Next.js", "Tailwind CSS", "Typescript"],
      //   info: ["SI 프로젝트 기초 설계를 위한 Boiler Plate 개발"],
      //   role: [
      //     "Tailwind CSS 이용하여 Common Atomic Component 개발 (Button, Input, Datepicker...)",
      //     "NextJS, Ant Design, SASS 이용하여 Common Atomic Component 개발(Button, Input ...)",
      //     "UI Design 대응을 위해 NextJS Story Book 적용",
      //   ],
      //   purpose: [
      //     "초기 개발에 쉽고 빠르게 대응하기 위해 통일된 구조로 프로젝트 구성",
      //     "사내 개발자들의 프로젝트 접근 용이성 추구",
      //   ],
      //   result: ["SI 프로젝트 설계 진행중"],
      // },
      // {
      //   title: "RAiDEA 서비스 관리자용 Admin Page 개발 및 유지보수",
      //   due: "2021-12 ~ 진행중",
      //   code: "C0002",
      //   description: "Admin Page F/E 개발 및 유지보수",
      //   icon: "dev",
      //   skill: [
      //     "React",
      //     "Redux",
      //     "Ant Design",
      //     "Styled Components",
      //     "javascript",
      //   ],
      //   info: [
      //     "Mobility Service Platform RAiDEA 서비스의 Admin Page 개발 및 런칭, 유지보수 진행중",
      //     "성능향상을 위한 지속적인 Refactoring 및 신기술 도입하여 개발 진행",
      //     "주1회 Scrum 회의 및 Code Review를 통하여 Code 개선 및 개인 개발 능력 향상",
      //   ],
      //   role: [
      //     "자원 관리(차량, 스테이션, 거점, 카드, 단말, 모델 등등…) 메뉴 개발 및 유지보수",
      //     "예약 관리 메뉴 개발 및 유지보수",
      //     "Google Map Service 기반 geojson feature 관리",
      //   ],
      //   purpose: ["각 SO별 안정적인 서비스 운영을 위한 관리자 페이지 개발"],
      //   result: [
      //     "국 내외 다수 서비스 런칭 및 안정적인 서비스 제공 (Carplat, Turu Car, IDrive, Wayrent, Tourzy 등...)",
      //   ],
      // },
      // {
      //   title: "MSA 대응을 위한 BFF Service 개발 및 유지보수",
      //   due: "2021-12 ~ 진행중",
      //   code: "C0003",
      //   description: "MSA 대응을 위한 BFF 유지보수",
      //   icon: "system",
      //   skill: ["Typescript", "nest"],
      //   info: ["Back end MSA 대응을 위한 BFF Service 개발 및 유지보수"],
      //   role: [
      //     "BE Service와의 연동을 위한 비즈니스 로직 관리",
      //     "FE 데이터 표출 대응을 위한 Type 및 Data 관리",
      //   ],
      //   purpose: ["FE – BE 의 안정적인 데이터 연동"],
      // },
    ],
  },
  {
    title: "(주)에코플래그 / 프론트엔드 개발자",
    team: "ITO사업본부 - 대리",
    due: "2020.11.23 ~ 2021.11.30 (1년)",
    img: "/images/career/ecoflag.png",
    skill: [
      "React",
      "javascript",
      "Java",
      "Spring",
      "Postgresql",
      "Jenkins",
      "Linux",
      "Apache Tomcat",
      "sass",
    ],
    project: [
      {
        title: "사물인터넷 기반 상수관망 수질 및 수량 저전력 계측 시스템 개발",
        due: "2021-07 ~ 2021-08",
        code: "C0004",
        description: "물, 수도 관련 SI 프로젝트 개발",
        icon: "dev",
        skill: ["React", "JAVA", "springboot", "Postgresql"],
        info: [
          "상수관망에 설치된 저전력 계측 시스템 데이터 연동",
          "실시간 데이터 표출(초단위) 및 차트 데이터 표출",
        ],
        role: ["Front-end, Back-end, DB 설계 및 개발"],
      },
      {
        title: "수돗물 수질 이상여부 진단 키트 개발",
        due: "2021-04 ~ 2021-07",
        code: "C0005",
        description: "물, 수도 관련 SI 프로젝트 개발",
        icon: "dev",
        skill: ["React", "JAVA", "springframework", "Postgresql"],
        info: [
          "수질 Kit를 분석하고 분석데이터를 저장하여 표출하는 시스템 개발",
          "Mobile Web Page로 카메라 사용을 위한 https 배포, 분석한 Kit 결과를 DB에 저장",
        ],
        role: [
          "Front-end, Back-end 개발",
          "개발 진행 중 인계받아 개발 마무리 및 고도화 개발 진행",
        ],
        result: [""],
      },
      {
        title:
          "비상운전(수계전환 등) 시 안전한 수돗물 공급을 위한 관로 운영지원시스템 구축",
        due: "2021-04 ~ 2021-07",
        code: "C0006",
        description: "물, 수도 관련 SI 프로젝트 개발",
        icon: "dev",
        skill: ["React", "JAVA", "springframework", "Postgresql"],
        info: [
          "수질 Kit를 분석하고 분석데이터를 저장하여 표출하는 시스템 개발",
          "반응형 WEB Page 개발, 실시간 분석 Data 관리 및 UI 표출",
        ],
        role: [
          "Front-end, Back-end 개발",
          "개발 진행 중 인계받아 개발 마무리 및 고도화 개발 진행",
        ],
      },
      {
        title: "아쿠아유나이티드 4.0 시스템 개발",
        due: "2021-04 ~ 2021-06",
        code: "C0007",
        description: "물, 수도 관련 SI 프로젝트 개발",
        icon: "dev",
        skill: [""],
        info: ["", "", ""],
        role: ["", "", ""],
        purpose: [""],
        result: [""],
      },
      {
        title: "물정보앱(Smart Water Grid) - 내부과제",
        due: "2021-03 ~ 2021-06",
        code: "C0008",
        description: "웹앱 개발 및 신입사원 교육자료 개발",
        icon: "setting",
        skill: ["javascript", "React", "JAVA", "eGovFramework", "JPA"],
        info: [
          "수질 정보 및 수도관 정보를 모바일에서 확인할 수 있는 Mobile WEB Page 개발",
        ],
        role: [
          "ERD, API설계 및 구축",
          "Web 페이지 구축 진행 (F/E, B/E)",
          "내부 과제로 개발 및 신입사원 교육과 같이 진행",
        ],
      },
      {
        title: "배출영향분석 표준 프로그램 유지관리(2021)",
        due: "2020-12 ~ 2021-08",
        code: "C0009",
        description: "환경부 주관 지자체 배출영향분석 프로그램 고도화",
        icon: "system",
        skill: ["Csharp", "Windows Form", "MSSQL", "install Shield"],
        info: ["C# Windows Forms 을 사용한 프로그램 유지관리"],
        role: [
          "프로젝트 관리 및 유지보수",
          "고객 요청사항에 맞게 수정 및 배포(InstallShield)",
        ],
      },
      {
        title: "전국오염원조사 DB 및 웹 시스템 구축(4)",
        due: "2020-11 ~ 2021-03",
        code: "C0010",
        description: "환경부 주관 전국오염원조사 고도화",
        icon: "system",
        skill: ["JAVA", "JSP", "Oracle", "JQuery", "HTML", "CSS"],
        info: [
          "전국오염원조사 홈페이지 (https://wems.nier.go.kr) 유지보수 및 고도화",
        ],
        role: [
          "고도화 개발 참여",
          "사용자 편의성을 위한 UI/UX개선 및 디자인 수정",
        ],
        purpose: [""],
        result: [""],
      },
    ],
  },
  {
    title: "(주)카피앤패이스트 / 웹 개발자",
    team: "미디어플랫폼팀 - 대리",
    due: "2016.11.07 ~ 2021.11.19 (4년)",
    img: "/images/career/cnp.png",
    skill: [
      "Java",
      "Spring",
      "Postgresql",
      "Mysql",
      "Redis",
      "Jenkins",
      "Linux",
      "Apache Tomcat",
      "javascript",
      "Angular",
    ],
    project: [
      {
        title: "KT Coupon Service 고도화",
        due: "2020-07 ~ 2020-09",
        code: "C0011",
        description: "서비스 연동방식 변경으로 인한 Proxy API Gateway 구축",
        icon: "system",
        skill: [""],
        info: ["", "", ""],
        role: ["", "", ""],
        purpose: [""],
        result: [""],
      },
      {
        title: "마이크로템플릿 WEBAPP Service 고도화",
        due: "2020-06 ~ 2020-09",
        code: "C0012",
        description: "WEBAPP 고도화",
        icon: "html",
        skill: [""],
        info: ["", "", ""],
        role: ["", "", ""],
        purpose: [""],
        result: [""],
      },
      {
        title: "Golfzon Matrix view",
        due: "2019-06 ~ 2019-11",
        code: "C0013",
        description: "서비스 개발 (스트리머 서버)",
        icon: "system",
        skill: [""],
        info: ["", "", ""],
        role: ["", "", ""],
        purpose: [""],
        result: [""],
      },
      {
        title: "Skylife PPV Service 개발",
        due: "2018-02 ~ 2018-09",
        code: "C0014",
        description: "STB WEBAPP 설계 및 개발",
        icon: "html",
        skill: [""],
        info: ["", "", ""],
        role: ["", "", ""],
        purpose: [""],
        result: [""],
      },
      {
        title: "OTT Telebee 통합관리 시스템 구축 및 개발",
        due: "2017-03 ~ 2017-09",
        code: "C0015",
        description: "CMS/BMS/API 개발",
        icon: "dev",
        skill: [""],
        info: ["", "", ""],
        role: ["", "", ""],
        purpose: [""],
        result: [""],
      },
      {
        title: "인터렉티브 타임슬라이스 시스템 개발",
        due: "2016-12 ~ 2019-03",
        code: "C0016",
        description: "시스템 개발",
        icon: "setting",
        skill: [""],
        info: ["", "", ""],
        role: ["", "", ""],
        purpose: [""],
        result: [""],
      },
    ],
  },
];
